# Generated by Django 4.2.3 on 2023-07-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='rec_c',
            field=models.IntegerField(default=1),
        ),
    ]
